In [35]:
#import libraries
import numpy as np
import matplotlib.pyplot as plt
import math
import random
import scipy

#LDPC codes

##1.

Write a function that receives a parity check matrix H and builds a systematic encoding matrix G for it. The function should return two matrices: ˆH and G, such that ˆH is equal to H up to a column permutation and ˆHGt = 0 for all t.

In [36]:
#initialize H
H = np.array([[1, 1, 1, 1, 0, 0],[0, 0, 1, 1, 0, 1],[1, 0, 0, 1, 1, 0]], dtype=int)

print(H)


[[1 1 1 1 0 0]
 [0 0 1 1 0 1]
 [1 0 0 1 1 0]]


In [42]:
m, n = H.shape
k = n-m

print(n,k,m)

H[0,:]
    

6 3 3


array([1, 1, 1, 1, 0, 0])

In [51]:
def ref(H):
    ''' return row echelon form'''
    m, n = H.shape
    k = n-m

    #copy H so that no switches/edits are applied
    H_hat = H.copy()

    if m == 0 or n==0:
        return H_hat
    
    for row in range(m):

        #search for 1 in first column
        if (H_hat[row,0]!= 0):
            break

    #if this is not the first row, switch
    if row>0:
        copy_row = H_hat[row].copy()
        H_hat[row]= H_hat[0]
        H_hat[0] = copy_row
    
    #add new row 1 to all rows with 1 in first col
    for rows_below in range(1,m):
        if (H_hat[rows_below,0]!=0):
            H_hat[rows_below,:] = (H_hat[0,:] + H_hat[rows_below,:]) % 2
    
    #then proceed to second row, second col and do the same and so on
    H_sub = ref(H_hat[1:m,1:n])

    #return row echelon form, add first col and first row back on
    return np.vstack([H_hat[:,0],np.hstack([H_hat[0,:], H_sub])])
        

